version: '3.8'

services:
  auth-service:
    container_name: auth-service
    image: ${DOCKER_USERNAME}/auth-service:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - backend

  mongodb:
    image: mongo:8.0
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:

networks:
  backend:
    external: true