version: '3.8'

services:
  auth-service:
    container_name: auth-service
    image: ${DOCKER_USERNAME}/auth-service:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true