Server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  profiles:
    active: dev

  #  data:
#    mongodb:
#      uri: mongodb+srv://...
#      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379
    username: redis123
    password: 1234

  coolsms:
    api-key: ${COOLSMS_API_KEY}
    api-secret: ${COOLSMS_API_SECRET}
    sender: ${COOLSMS_SENDER}

  config:
    import: optional:file:.env[.properties]

eureka:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EC2_HOST}:8761/eureka/

JWT:
  secret-key: ${JWT_SECRET_KEY}
  token:
    access-expire-time: 1800000000
    refresh-expire-time: 1209600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

