spring:
  config:
    import: optional:dotenv:.env
  datasource:
    url: jdbc:mysql://${EC2_HOST}:3306/piece_of_cake
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${EC2_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

    mongodb:
      uri: mongodb://${EC2_MONGOID}:${EC2_MONGOPW}@${EC2_HOST}:27017/auth-service
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://${EC2_HOST:localhost}:8761/eureka/