spring:
  datasource:
    url: jdbc:mysql://localhost:3306/piece_of_cake_local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
    mongodb:
      uri: mongodb://admin:admin123@127.0.0.1:27020/auth-service?authSource=admin
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/