Server:
  port: 8081

spring:
  application:
    name: auth-service

#  data:
#    mongodb:
#      uri: mongodb+srv://...
#      auto-index-creation: true

  DataSource:
    url: jdbc:mysql://localhost:3306/piece_of_cake_local

    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    username: redis123
    password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

JWT:
  secret-key: e70a7f3ba3456c05be96f2b804fea1b41688111d051a43e28e9c25d2e430b4b8
  token:
    access-expire-time: 3600
