spring:
  datasource:
    url: jdbc:mysql://localhost:3306/piece_of_cake_local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379
      username: redis123
      password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/